//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMgmtMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employpersonal
    {
        public int id { get; set; }
        public string employid { get; set; }
        public string employfullname { get; set; }
        public string employdob { get; set; }
        public string employgender { get; set; }
        public string employbloodgrp { get; set; }
        public string employmobno1 { get; set; }
        public string employmobno2 { get; set; }
        public string employmailid { get; set; }
        public string employaddress { get; set; }
        public string employqualification { get; set; }
        public string employdesignation { get; set; }
    }
}
